on:
  # 手动触发事件
  workflow_dispatch:

name: trigger transfer test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run:
          mvn clean package --file pom.xml
